[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
auto_detect_solc = false
evm_version = "osaka"
optimizer = true
optimizer_runs = 10000
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
libraries = []
fs_permissions = [{ access = "read-write", path = "./snapshots" }]