name: Upgrade

permissions: {}

on:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Upgrade from 1.0.1
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive
          # test-upgrade.bash checks out the 1.0.1 tag
          fetch-depth: 0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.8.3

      - name: Run upgrade test
        run: make test-upgrade
